version: "3.8"
services:
  server:
    build:
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://db:27017/chattapp
  
  client:
    build:
      dockerfile: Dockerfile.client
      args:
        REACT_APP_URL: http://localhost:3001
    ports:
      - "3000:3000"
  db:
    image: mongo:6.0.2
    ports:
      - "27017:27017"
    container_name: db_chattapp
    volumes:
      - /data/db

