FROM node:16-alpine
WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/server/package*.json ./packages/server/
COPY ./packages/shared/package*.json ./packages/shared/

RUN npm ci -w packages/server

COPY ./packages/server ./packages/server
COPY ./packages/shared ./packages/shared

ARG SECRET_TOKEN 
ENV JWT_SECRET=${SECRET_TOKEN}

RUN npm run build -w packages/server

EXPOSE 3001

CMD [ "node", "packages/server/dist/server.js" ]