FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/client/package*.json ./packages/client/
COPY ./packages/shared/package*.json ./packages/shared/

RUN npm ci -w packages/client

COPY ./packages/client ./packages/client
COPY ./packages/shared ./packages/shared

ARG REACT_APP_URL
ENV REACT_APP_BASE_URL=${REACT_APP_URL}

RUN npm run build -w packages/client
EXPOSE 3000

CMD [ "npx", "serve", "-s", "packages/client/build" ]